/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AttendanceStatus = IDL.Variant({
  'no' : IDL.Null,
  'yes' : IDL.Null,
  'maybe' : IDL.Null,
});
export const Rsvp = IDL.Record({
  'id' : IDL.Nat,
  'status' : AttendanceStatus,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  'getAllRsvps' : IDL.Func([], [IDL.Vec(Rsvp)], ['query']),
  'getRsvpById' : IDL.Func([IDL.Nat], [Rsvp], ['query']),
  'getRsvpStats' : IDL.Func([], [IDL.Nat, IDL.Nat, IDL.Nat], ['query']),
  'getRsvpsByStatus' : IDL.Func([AttendanceStatus], [IDL.Vec(Rsvp)], ['query']),
  'submitRsvp' : IDL.Func(
      [IDL.Text, IDL.Text, AttendanceStatus, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AttendanceStatus = IDL.Variant({
    'no' : IDL.Null,
    'yes' : IDL.Null,
    'maybe' : IDL.Null,
  });
  const Rsvp = IDL.Record({
    'id' : IDL.Nat,
    'status' : AttendanceStatus,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    'getAllRsvps' : IDL.Func([], [IDL.Vec(Rsvp)], ['query']),
    'getRsvpById' : IDL.Func([IDL.Nat], [Rsvp], ['query']),
    'getRsvpStats' : IDL.Func([], [IDL.Nat, IDL.Nat, IDL.Nat], ['query']),
    'getRsvpsByStatus' : IDL.Func(
        [AttendanceStatus],
        [IDL.Vec(Rsvp)],
        ['query'],
      ),
    'submitRsvp' : IDL.Func(
        [IDL.Text, IDL.Text, AttendanceStatus, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };