/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AttendanceStatus = { 'no' : null } |
  { 'yes' : null } |
  { 'maybe' : null };
export interface Rsvp {
  'id' : bigint,
  'status' : AttendanceStatus,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
}
export interface _SERVICE {
  'getAllRsvps' : ActorMethod<[], Array<Rsvp>>,
  'getRsvpById' : ActorMethod<[bigint], Rsvp>,
  'getRsvpStats' : ActorMethod<[], [bigint, bigint, bigint]>,
  'getRsvpsByStatus' : ActorMethod<[AttendanceStatus], Array<Rsvp>>,
  'submitRsvp' : ActorMethod<
    [string, string, AttendanceStatus, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];