/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Rsvp {
    id: bigint;
    status: AttendanceStatus;
    name: string;
    email: string;
    message: string;
    timestamp: bigint;
}
export enum AttendanceStatus {
    no = "no",
    yes = "yes",
    maybe = "maybe"
}
export interface backendInterface {
    getAllRsvps(): Promise<Array<Rsvp>>;
    getRsvpById(id: bigint): Promise<Rsvp>;
    getRsvpStats(): Promise<[bigint, bigint, bigint]>;
    getRsvpsByStatus(status: AttendanceStatus): Promise<Array<Rsvp>>;
    submitRsvp(name: string, email: string, status: AttendanceStatus, message: string): Promise<void>;
}
import type { AttendanceStatus as _AttendanceStatus, Rsvp as _Rsvp } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getAllRsvps(): Promise<Array<Rsvp>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRsvps();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRsvps();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRsvpById(arg0: bigint): Promise<Rsvp> {
        if (this.processError) {
            try {
                const result = await this.actor.getRsvpById(arg0);
                return from_candid_Rsvp_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRsvpById(arg0);
            return from_candid_Rsvp_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRsvpStats(): Promise<[bigint, bigint, bigint]> {
        if (this.processError) {
            try {
                const result = await this.actor.getRsvpStats();
                return [
                    result[0],
                    result[1],
                    result[2]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRsvpStats();
            return [
                result[0],
                result[1],
                result[2]
            ];
        }
    }
    async getRsvpsByStatus(arg0: AttendanceStatus): Promise<Array<Rsvp>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRsvpsByStatus(to_candid_AttendanceStatus_n6(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRsvpsByStatus(to_candid_AttendanceStatus_n6(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitRsvp(arg0: string, arg1: string, arg2: AttendanceStatus, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitRsvp(arg0, arg1, to_candid_AttendanceStatus_n6(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitRsvp(arg0, arg1, to_candid_AttendanceStatus_n6(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
}
function from_candid_AttendanceStatus_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AttendanceStatus): AttendanceStatus {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Rsvp_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Rsvp): Rsvp {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _AttendanceStatus;
    name: string;
    email: string;
    message: string;
    timestamp: bigint;
}): {
    id: bigint;
    status: AttendanceStatus;
    name: string;
    email: string;
    message: string;
    timestamp: bigint;
} {
    return {
        id: value.id,
        status: from_candid_AttendanceStatus_n4(_uploadFile, _downloadFile, value.status),
        name: value.name,
        email: value.email,
        message: value.message,
        timestamp: value.timestamp
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    no: null;
} | {
    yes: null;
} | {
    maybe: null;
}): AttendanceStatus {
    return "no" in value ? AttendanceStatus.no : "yes" in value ? AttendanceStatus.yes : "maybe" in value ? AttendanceStatus.maybe : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Rsvp>): Array<Rsvp> {
    return value.map((x)=>from_candid_Rsvp_n2(_uploadFile, _downloadFile, x));
}
function to_candid_AttendanceStatus_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AttendanceStatus): _AttendanceStatus {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AttendanceStatus): {
    no: null;
} | {
    yes: null;
} | {
    maybe: null;
} {
    return value == AttendanceStatus.no ? {
        no: null
    } : value == AttendanceStatus.yes ? {
        yes: null
    } : value == AttendanceStatus.maybe ? {
        maybe: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
